data_br<-read.csv("/home/prithvirajhi/new_thesis/Thesis/new_script/Logs/new_logs/bridge/new3.csv", sep=" ")
data_flow<-read.csv("/home/prithvirajhi/new_thesis/Thesis/new_script/Logs/new_logs/Pred/new4.csv", sep=" ")
pdf(file="/home/prithvirajhi/new_thesis/Thesis/new_script/R/throughput.pdf", width=7, height=3.5)
plot(data_br[,1], data_br[,2], type='l', col="red", axes=FALSE, xlab="Time (s)", ylab="Throughput (Mbps)", ylim=c(0, 12))
axis(side=1, at=seq(from=0, to=18, by=1))
axis(side=2, at=seq(from=0, to=12, by=2))
lines(data_br[,1], data_flow[,2], type='l', lty=5, col="green")
legend(x=0, y=4, legend=c("Bridge configuration", "ÆtherFlow configuration with prediction"), col=c("red", "green"), lty=c(1, 5), bty="n", cex=0.7)
abline(v=7)
box()
dev.off()
pdf(file="/home/prithvirajhi/new_thesis/Thesis/new_script/R/loss.pdf", width=7, height=3.5)
plot(data_br[,1], data_br[,3], type='l', col="red", axes=FALSE, xlab="Time (s)", ylab="Loss rate (%)", ylim=c(0, 100))
axis(side=1, at=seq(from=0, to=18, by=1))
axis(side=2, at=seq(from=0, to=100, by=20))
lines(data_br[,1], data_flow[,3], type='l', lty=5, col="green")
legend(x=0, y=100, legend=c("Bridge configuration", "ÆtherFlow configuration with prediction"), col=c("red", "green"), lty=c(1, 5), bty="n", cex=0.7)
abline(v=7)
box()
dev.off()
